site_name: ASP.Net Core
site_description: ASP.Net Core
site_author: MOGHA
docs_dir: docs

theme:
  name: material
  language: fa

  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.suggest
    - search.share

  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: حالت تاریک

    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: حالت روشن

  font:
    text: Vazirmatn
    code: JetBrains Mono

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.emoji

extra_css:
  - assets/extra.css

nav:
  - خانه: index.md

  - مقدمه و راه اندازی:
      - کامپیوتر چگونه کار می‌کند؟: "مقدمه و راه اندازی (Introduction & Environment Setup)/1. کامپیوتر چگونه کار می‌کند؟.md"
      - مقدمه‌ای بر زبان‌های برنامه‌نویسی: "مقدمه و راه اندازی (Introduction & Environment Setup)/2. مقدمه‌ای بر زبان‌های برنامه‌نویسی.md"
      - نحوه کار برنامه‌های کامپیوتری: "مقدمه و راه اندازی (Introduction & Environment Setup)/3. نحوه کار برنامه‌های کامپیوتری.md"
      - انواع مختلف کاربردها: "مقدمه و راه اندازی (Introduction & Environment Setup)/4. انواع مختلف کاربردها.md"
      - روش‌شناسی‌های برنامه‌نویسی: "مقدمه و راه اندازی (Introduction & Environment Setup)/5.روش‌شناسی‌های برنامه‌نویسی.md"
      - الگوریتم، شبه‌کد، برنامه‌ها و فلوچارت‌ها: "مقدمه و راه اندازی (Introduction & Environment Setup)/6. الگوریتم، شبه‌کد، برنامه‌ها و فلوچارت‌ها.md"
      - مقدمه‌ای بر چارچوب دات‌نت: "مقدمه و راه اندازی (Introduction & Environment Setup)/7. مقدمه‌ای بر چارچوب دات‌نت.md"
      - معماری و اجزای چارچوب دات نت: "مقدمه و راه اندازی (Introduction & Environment Setup)/8. معماری و اجزای چارچوب دات نت.md"
      - مقدمه‌ای بر زبان برنامه‌نویسی سی‌شارپ: "مقدمه و راه اندازی (Introduction & Environment Setup)/9. مقدمه‌ای بر زبان برنامه‌نویسی سی‌شارپ.md"
      - نقشه راه توسعه‌دهندگان دات‌نت برای سال 2025: "مقدمه و راه اندازی (Introduction & Environment Setup)/10. نقشه راه توسعه‌دهندگان دات‌نت برای سال 2025.md"
      - بهترین روش‌های استاندارد کدنویسی: "مقدمه و راه اندازی (Introduction & Environment Setup)/11. بهترین روش‌های استاندارد کدنویسی.md"

  - C#:
      - مقدمه سی شارپ (C#.NET Basics):
          - ساختار اولیه برنامه سی شارپ: "C#/مقدمه سی شارپ (C#.NET Basics)/1 .ساختار اولیه برنامه سی شارپ.md"
          - متدها و ویژگی‌های کلاس کنسول: "C#/مقدمه سی شارپ (C#.NET Basics)/2. متدها و ویژگی‌های کلاس کنسول در سی شارپ.md"
          - انواع داده: "C#/مقدمه سی شارپ (C#.NET Basics)/3. انواع داده در سی شارپ.md"
          - لیترال‌ها: "C#/مقدمه سی شارپ (C#.NET Basics)/4. لیترال‌ها در سی شارپ.md"
          - تبدیل نوع: "C#/مقدمه سی شارپ (C#.NET Basics)/5. تبدیل نوع در سی شارپ.md"
          - متغیرها: "C#/مقدمه سی شارپ (C#.NET Basics)/6. متغیرها در سی شارپ.md"
          - عملگرها: "C#/مقدمه سی شارپ (C#.NET Basics)/7. عملگرها در سی شارپ.md"
          - دستورات جریان کنترل: "C#/مقدمه سی شارپ (C#.NET Basics)/8. دستورات جریان کنترل در سی شارپ.md"
          - دستورات If-Else: "C#/مقدمه سی شارپ (C#.NET Basics)/9. دستورات If-Else در سی شارپ.md"
          - دستورات Switch: "C#/مقدمه سی شارپ (C#.NET Basics)/10. دستورات سوئیچ در سی شارپ.md"
          - حلقه‌ها: "C#/مقدمه سی شارپ (C#.NET Basics)/11. حلقه‌ها در سی شارپ.md"
          - حلقه While: "C#/مقدمه سی شارپ (C#.NET Basics)/12. حلقه while در سی شارپ.md"
          - حلقه Do While: "C#/مقدمه سی شارپ (C#.NET Basics)/13 . حلقه Do While در سی شارپ.md"
          - حلقه For: "C#/مقدمه سی شارپ (C#.NET Basics)/14. حلقه For در سی شارپ.md"
          - دستور Break: "C#/مقدمه سی شارپ (C#.NET Basics)/15. دستور break در سی شارپ.md"
          - دستور Continue: "C#/مقدمه سی شارپ (C#.NET Basics)/16. دستور Continue در سی شارپ.md"
          - دستور Goto: "C#/مقدمه سی شارپ (C#.NET Basics)/17. دستور Goto در سی شارپ.md"
          - توابع: "C#/مقدمه سی شارپ (C#.NET Basics)/18. توابع در سی شارپ.md"
          - توابع تعریف‌شده توسط کاربر: "C#/مقدمه سی شارپ (C#.NET Basics)/19. توابع تعریف شده توسط کاربر در سی شارپ.md"
          - فراخوانی با مقدار و ارجاع: "C#/مقدمه سی شارپ (C#.NET Basics)/20. فراخوانی با مقدار و فراخوانی با ارجاع در سی شارپ.md"
          - بازگشت: "C#/مقدمه سی شارپ (C#.NET Basics)/21. بازگشت در سی شارپ.md"
          - ورودی و خروجی کاربر: "C#/مقدمه سی شارپ (C#.NET Basics)/22. ورودی و خروجی کاربر در سی شارپ.md"
          - آرگومان‌های خط فرمان: "C#/مقدمه سی شارپ (C#.NET Basics)/23. آرگومان‌های خط فرمان در سی شارپ.md"
          - رشته‌ها: "C#/مقدمه سی شارپ (C#.NET Basics)/24. رشته در سی شارپ.md"
          - کلمه کلیدی static: "C#/مقدمه سی شارپ (C#.NET Basics)/25. کلمه کلیدی استاتیک در سی شارپ.md"
          - اعضای استاتیک و غیر استاتیک: "C#/مقدمه سی شارپ (C#.NET Basics)/26. اعضای استاتیک در مقابل اعضای غیر استاتیک در سی شارپ.md"
          - Const و ReadOnly: "C#/مقدمه سی شارپ (C#.NET Basics)/27. Const و Read-Only در سی شارپ.md"
          - Properties: "C#/مقدمه سی شارپ (C#.NET Basics)/28. Properties در سی شارپ.md"
          - Override متد ToString: "C#/مقدمه سی شارپ (C#.NET Basics)/29. چرا باید متد ToString را در سی شارپ Override کنیم؟.md"
          - Override متد Equals: "C#/مقدمه سی شارپ (C#.NET Basics)/30. نادیده گرفتن متد Equals در سی شارپ.md"
          - Convert.ToString و ToString: "C#/مقدمه سی شارپ (C#.NET Basics)/31. تفاوت بین Convert.ToString و متد ToString در سی شارپ.md"
          - Checked و Unchecked: "C#/مقدمه سی شارپ (C#.NET Basics)/32. کلمات Checked و Unchecked در سی شارپ.md"
          - Stack و Heap: "C#/مقدمه سی شارپ (C#.NET Basics)/33. Stack و Heap در .net.md"
          - Boxing و Unboxing: "C#/مقدمه سی شارپ (C#.NET Basics)/34. Boxing و Unboxing در سی شارپ.md"