site_name: ASP.Net Core
site_description: ASP.Net Core
site_author: MOGHA
docs_dir: docs

theme:
  name: material
  language: fa

  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.suggest
    - search.share

  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: حالت تاریک

    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: حالت روشن

  font:
    text: Vazirmatn
    code: JetBrains Mono

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.emoji

extra_css:
  - assets/extra.css

nav:
  - خانه: index.md

  - شروع کار:
      - شروع کار با ASP.NET Core: "1. شروع کار با ASP.NET Core.md"

  - آموزش‌ها:
      - وب اپ‌ها:
          - انتخاب رابط کاربری (Web UI): "2. آموزش ها/1. وب اپ ها/1. انتخاب رابط کاربری (Web UI) در ASP.NET Core.md"
          - Razor Pages:
              - آموزش ساخت یک برنامه وب: "2. آموزش ها/1. وب اپ ها/2.  Razor Pages/1. آموزش ساخت یک برنامه وب با Razor Pages در ASP.NET Core.md"
              - شروع کار با Razor Pages: "2. آموزش ها/1. وب اپ ها/2.  Razor Pages/2. شروع کار با Razor Pages در ASP.NET Core.md"
              - افزودن Model به برنامه: "2. آموزش ها/1. وب اپ ها/2.  Razor Pages/3. آموزش افزودن Model به برنامه Razor Pages.md"